/*
 * File: app/view/MainViewportViewController.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Entregas100Web.view.MainViewportViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.mainviewport',

    abrirPanel: function(panelAlias, panelConfig) {
        var me = this,
            tabContainer = me.view.down("#tabContainer"),
            panel = tabContainer.down("> panel[alias=" + panelAlias + "]");

        if (!panel) {
            panel = Ext.create(panelAlias, panelConfig);
            tabContainer.add(panel);
        }

        tabContainer.setActiveTab(panel);
    },

    onMItemPlazasClick: function(item, e, eOpts) {
        this.abrirPanel("widget.plazaspanel");
    },

    onMItemFormasPagoClick: function(item, e, eOpts) {
        this.abrirPanel("widget.formaspagopanel");
    },

    onMItemPerfilesPagoClick: function(item, e, eOpts) {
        this.abrirPanel("widget.perfilespagopanel");
    },

    onMItemPerfilesPagoClick12: function(item, e, eOpts) {
        this.abrirPanel("widget.tablapuntospanel");
    },

    onMItemPerfilesPagoClick11: function(item, e, eOpts) {
        this.abrirPanel("widget.usuariospanel");
    },

    onMItemPerfilesPagoClick1: function(item, e, eOpts) {
        this.abrirPanel("widget.permisospanel");
    },

    onMItemManguerasClick: function(item, e, eOpts) {
        this.abrirPanel("widget.mangueraspanel");
    },

    onMItemReportesAlarmasClick: function(item, e, eOpts) {
        var me = this;

        me.abrirPanel("widget.reportesalarmaspanel");
    },

    onMItemScriptRemotoClick: function(item, e, eOpts) {
        this.abrirPanel("widget.scriptremotopanel");
    },

    onMItemConfigurarCuentaClick: function(item, e, eOpts) {
        this.abrirPanel("widget.configurarcuentapanel");
    },

    onMItemCerrarSesionClick: function(item, e, eOpts) {
        var me = this;

        Ext.Msg.confirm(
        "Mensaje del sistema",
        "¿Desea cerrar sesión?",
        function(result) {
            if (result == "yes") {
                me.view.destroy();
                Ext.create("Entregas100Web.view.LoginWindow", {});
            }
        }
        );
    }

});
